/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author HP
 */
public class Fr_administracion extends javax.swing.JFrame {

    /**
     * Creates new form Fr_administracion
     */
    public Fr_administracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEscritorio = new javax.swing.JDesktopPane();
        jButtonSalirAdmin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuItemPersona = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemProducto = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPaneEscritorio.setBackground(new java.awt.Color(102, 102, 255));

        jButtonSalirAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSalirAdmin.setText("Salir");

        jDesktopPaneEscritorio.setLayer(jButtonSalirAdmin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneEscritorioLayout.createSequentialGroup()
                .addContainerGap(1038, Short.MAX_VALUE)
                .addComponent(jButtonSalirAdmin)
                .addGap(29, 29, 29))
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneEscritorioLayout.createSequentialGroup()
                .addContainerGap(592, Short.MAX_VALUE)
                .addComponent(jButtonSalirAdmin)
                .addGap(24, 24, 24))
        );

        jMenuConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/btnconfig.png"))); // NOI18N

        jMenuItemPersona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/icon_cliente.png"))); // NOI18N
        jMenuItemPersona.setText("Persona");
        jMenuItemPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPersonaActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItemPersona);

        jMenuItemUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/icon-usuario.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuario");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItemUsuario);

        jMenuItemProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/boxes.png"))); // NOI18N
        jMenuItemProducto.setText("Productos");
        jMenuItemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductoActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItemProducto);

        jMenuBar1.add(jMenuConfiguracion);

        jMenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/btnReportes.png"))); // NOI18N
        jMenuBar1.add(jMenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPersonaActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProductoActionPerformed

    public JButton getjButtonSalirAdmin() {
        return jButtonSalirAdmin;
    }

    public void setjButtonSalirAdmin(JButton jButtonSalirAdmin) {
        this.jButtonSalirAdmin = jButtonSalirAdmin;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPaneEscritorio;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPaneEscritorio = jDesktopPane1;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getjMenuConfiguracion() {
        return jMenuConfiguracion;
    }

    public void setjMenuConfiguracion(JMenu jMenuConfiguracion) {
        this.jMenuConfiguracion = jMenuConfiguracion;
    }

    public JMenuItem getjMenuItemPersona() {
        return jMenuItemPersona;
    }

    public void setjMenuItemPersona(JMenuItem jMenuItemPersona) {
        this.jMenuItemPersona = jMenuItemPersona;
    }

    public JMenuItem getjMenuItemProducto() {
        return jMenuItemProducto;
    }

    public void setjMenuItemProducto(JMenuItem jMenuItemProducto) {
        this.jMenuItemProducto = jMenuItemProducto;
    }

    public JMenuItem getjMenuItemUsuario() {
        return jMenuItemUsuario;
    }

    public void setjMenuItemUsuario(JMenuItem jMenuItemUsuario) {
        this.jMenuItemUsuario = jMenuItemUsuario;
    }

    public JMenu getjMenuReportes() {
        return jMenuReportes;
    }

    public void setjMenuReportes(JMenu jMenuReportes) {
        this.jMenuReportes = jMenuReportes;
    }

    public JDesktopPane getjDesktopPaneEscritorio() {
        return jDesktopPaneEscritorio;
    }

    public void setjDesktopPaneEscritorio(JDesktopPane jDesktopPaneEscritorio) {
        this.jDesktopPaneEscritorio = jDesktopPaneEscritorio;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalirAdmin;
    private javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenuItem jMenuItemPersona;
    private javax.swing.JMenuItem jMenuItemProducto;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuReportes;
    // End of variables declaration//GEN-END:variables
}
